// レポートラベル
export const ReportLabel = {
    TITLE: 'レポート出力イメージ②　サマリー',
    // SECRET_CONFIDENTIAL: 'Confidential',
    // DESCRIPTION: '親口座⇔全子口座間プーリング金額・利息金額の合算、累計のインターカンパニーローン残高、親口座の口座残高を表示',
    SCHEME_NAME: 'Scheme Name',
    FROM: 'From',
    TO: 'To',
    ASOF: 'As of',
    REFERENCE: '*Reference',
    DATE: 'Date',
    CSA: 'Consolidated Sweep Amount',
    DEBIT: 'Debit(From Header)' ,
    CREDIT: 'Credit(To Header)' ,
    ENDOFDAY: 'End of Day' ,
    BALANCE: 'Balance',
    CICLB: 'Consolidated Inter-Company Loan Balance',
    LENDING_BALANCE: 'Lending Balance',
    FROM_HEADER: '(From Header)',
    BORROWING_BALANCE: 'Borrowing Balance',
    FROM_PARTICIPANT: '(From Participant)',
    INTEREST: 'Interest',
    LENDING: '(Lending)',
    BORROWING: '(Borrowing)',
    WHT_INTEREST: 'WHT for Interest',
    A: '(A)',
    B: '(B)',
    C: '(C)',
    D: '(D)',
    A_MINUS_B: '(A)-(B)',
    C_MINUS_D: '(C)-(D)',
    CI: 'Consolidated Inter-',
    CLB: 'Company Loan Balance',
    TOTAL_INTEREST: 'Total Interest'
};
